import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Personal/Navbar";
import NavbarNew from "@/Components/Personal/NavbarNewVariant";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Framer + Tailwind components",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  {/* <Navbar /> */}
  return (
    <html lang="en">
      <body className={"overflow-x-hidden overflow-y-hidden"}>
        <NavbarNew/>
        {children}
      </body>
    </html>
  );
}
